# Use edge weights in graph
weighted_graph: False
# Node2vec hyper params
dimensions: 64
walk_length: 10
num_walks: 300
window: 10
min_count: 1
batch_words: 4
seed: 1
#Epochs
iter: 5
# n cpus to use (null = cpu.count())
workers: 2
# no file type suffix
embeddings_filename: "n2v_node_embeddings"
#run_link_generation will only upload models called n2v.model
model_filename: "n2v_200.model"
#run_link_generation.sh is only going to find and upload files with 'suggested_related_links' in the filename to aws
predictions_filename: "suggested_related_links"
